name: PushAlarm
options:
  bundleIdPrefix: com.brenobrum.pushalarm
  deploymentTarget:
    iOS: "26.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: B7524C64B4
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  PushAlarm:
    type: application
    platform: iOS
    sources: [PushAlarm, Shared]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brenobrum.pushalarm
        CODE_SIGN_ENTITLEMENTS: PushAlarm/PushAlarm.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: PushAlarm
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_FILE: PushAlarm/Info.plist
    dependencies:
      - target: NotificationService
  NotificationService:
    type: app-extension
    platform: iOS
    sources: [NotificationService, Shared]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brenobrum.pushalarm.NotificationService
        INFOPLIST_KEY_CFBundleDisplayName: PushAlarm
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_ENTITLEMENTS: NotificationService/NotificationService.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: NotificationService/Info.plist
